### ISSUE TITLE
"INVALID code" on former tags

### ISSUE THREAD

**Issue by AndreasNH** [cybernetisk/fordelingsutvalget#14]
Om en bruker et tidligere navn på foreninger i not_attending: feltet i møterererater, så vil dette produsere en feilmelding på nettsiden. Dette kan skape problemer i fremtiden om foreninger bytter navn. 
```
not_attending:
    - prognett
```
![skjermbilde 2018-07-09 01 41 48](https://user-images.githubusercontent.com/15560573/42425176-43a1446e-8319-11e8-9cd5-0a3d69f38e69.png)

Nye tags fungerer helt fint.
```
not_attending:
    - progsys
```
![skjermbilde 2018-07-09 01 43 59](https://user-images.githubusercontent.com/15560573/42425192-9766fc2e-8319-11e8-93cc-62fab1d6ba7d.png)

**Comment by thor** [comment]
Man har vel to valg:

1. Behandle de som unike ID-er som ikke muterer.
2. Opprett en ny datafil eller nye felt for å finne ut om en forening har byttet navn.

**Comment by AndreasNH** [comment]
Vi har et felt i fila `/_data/associations.yml` som heter `former_tag:`. 
Det er vel mulig å kjøre en `or` test eller annet sted. Har ikke satt meg inn i logikken for å koble foreninger opp mot tags enda.

**Comment by N0K0** [comment]
Har en fiks for det. Må bare logikke litt mer. Her minimal viable producter man hele vegen
