### ISSUE TITLE
Endre vedtekter

### ISSUE THREAD

**Issue by AndreasNH** [cybernetisk/fordelingsutvalget#24]
Vedtektene kunne trengt en gjennomgang, da mye av infoen er utdatert. 

 [Vedtekter](https://github.com/cybernetisk/fordelingsutvalget/blob/master/pages/2016-09-02-vedtekter.md)

**Comment by N0K0** [comment]
Vi må fikse paragraf §10 når det kommer til sparing

**Comment by AndreasNH** [comment]
@N0K0 Noe mer vi manger nå i vedtektene?
