### ISSUE TITLE
Vedtekter og retningslinjer ikke lett tilgjengelig

### ISSUE THREAD

**Issue by thor** [cybernetisk/fordelingsutvalget#25]
Både /vedtekter/ og /retningslinjer/ er på siden, men er ikke lett tilgjengelig da de ikke er lenket til.

**Comment by AndreasNH** [comment]
Begge er linket til under [/apply/](https://fordelingsutvalget.org/apply/). (da med noe utdatert brødtekst)
Vi kan legge dem over møtereferatene i [/archive/](https://fordelingsutvalget.org/archive/) også. Da det var ca. sånn de var organisert på den gamle siden.

**Comment by thor** [comment]
Jeg ville foreslått å ev. ha det under "Om", men en egen side for
dokumenter høres langt i fra dumt ut.
