### ISSUE TITLE
Embedde søknadsformen rett inn i siden vår.

### ISSUE THREAD

**Issue by N0K0** [cybernetisk/fordelingsutvalget#36]
Ser på hvordan man legge til muligheter til å søke rett på FU siden. 

Ser på muligheter fra Cognitor og JotForm for å binde sammen med en pipeline fra Integromat eller Zapier for å kunne generere dokumentene vi trenger.

**Comment by N0K0** [comment]
Tester skjema under https://www.cognitoforms.com/FU6/SøknadsformFordelingsutvalget
Regner med at den lenken forblir statisk.

Videre pusher jeg dataen over integromat til google sheets.

**Comment by N0K0** [comment]
Ok. Oppdaterer skjema på cognitoforms som fordelingsutvalget.org/apply henter fra.
Ønsker man kanskje ett separat skjema for rapporter? 

@AndreasNH hva syns du om ønsket innhold? Samme som forrige skjema eller skal vi restrukturere litt igjen?

**Comment by AndreasNH** [comment]
Skjemaet ser veldig bra ut!  
Ønsker litt å ha rapportene for seg selv, da disse ofte lett blir borte / gjemt i andre dokumenter.

**Comment by N0K0** [comment]
Alrighty! Da fikser jeg det slik. Når skjemaet sendes inn gies også foreningen en ID på skjemaet, skal få dem til å måtte oppgi dette. Skal også få reregistrert den Cognito kontoen til en FU konto så den ikke ligger på meg :+1:

**Comment by N0K0** [comment]
Opprettet cognitoform og intergromatbruker for FU. Info har kommet i mail.
Overfører skjema og binningen til den brukeren.

**Comment by N0K0** [comment]
Setter opp integromat til å laste ned alle refererte filer til en mappe på driven også
