### ISSUE TITLE
Legge inn advarsler i gamle referater.

### ISSUE THREAD

**Issue by AndreasNH** [cybernetisk/fordelingsutvalget#38]
Jeg opprettet et nytt layout for å kunne ta høyde for en gammel referatstil det det ikke spesifisert hvem som har stemmerett. Dette lager bare unødvendig kompleksitet og blir et herk å vedlikeholde. Tenker å heller lage en advarsel i toppen på eldre referater om at det kan ha feil / mangler, samt å henvise til originalreferatet for korrekt info. 

Noen små sub tasks:
- [x] Opprette en include for advarsel.
- [x] Oppdatere referater med å legge inn advarsel og endre layout til `meeting`
- [x] Slette `meeting_old` samt relevant tull.

**Comment by N0K0** [comment]
Lagde akkurat #42. For noe der. Tenkte at i lengden er det nok greie om vi har en uniform layout for begge typene. Tenker hvis vi typ noensinne oppdatere layouten senere. Kan fikse med attributter i sakene senere. Går fort så snart alle saker har fått ny metainfo
