### ISSUE TITLE
Kombiner meetings layouts 

### ISSUE THREAD

**Issue by N0K0** [cybernetisk/fordelingsutvalget#42]
Ser vi ha en meeting og en old meeting layout. Skalerer nok bedre i det lange løp å ha dem som én og heller bruke ett attributt I det gamle sakene for legacy problemstillingen

**Comment by AndreasNH** [comment]
Lagde in include som jeg la inn øverst i alle referatene som det er aktuelt i. Tenkter det ikke er noen god grunn til å legge det inn i layouten og bruke ett attributt, da dette ikke vil oppstå igjen etter at alt er overført

**Comment by N0K0** [comment]
Jadda, det som skjer da er at man bare utelater attributtet I nye møter, det vil da defaulte til nytt layout. Blir toppen én ekstra linje I nåværende layout tenkte jeg :smile:
